---
title: "Dados do SIM"
date: now
lang: pt
format: html
editor: visual
---

## Pacotes

```{r}
library(tidyverse)
library(read.dbc)
library(lubridate)
```

## Leitura dos arquivos originais do SIM

```{r}
br2020 <- read.dbc(file = "../../data/raw/DOBR2020.dbc")
br2021 <- read.dbc(file = "../../data/raw/DOBR2021.dbc")

sim <- bind_rows(br2020, br2021) %>% as_tibble()
rm(br2020, br2021)
```

```{r}
write_rds(x = sim, file = "../../data/sim.rds")
```

## Filtro Covid-19

```{r}
sim_covid19 <- sim %>%
  mutate_at(c("CAUSABAS","LINHAA","LINHAB","LINHAC","LINHAD","LINHAII"), ~str_remove_all(., "[^[:alnum:]]")) %>%
  mutate_at(c("CAUSABAS","LINHAA","LINHAB","LINHAC","LINHAD","LINHAII"), ~str_replace_na(., "")) %>%
  mutate_at(c("CAUSABAS","LINHAA","LINHAB","LINHAC","LINHAD","LINHAII"), ~str_to_upper(., "")) %>%
  mutate(CODCAUSAS2 = str_c(CAUSABAS, LINHAA, LINHAB, LINHAC, LINHAD, LINHAII, sep = "")) %>%
  filter(str_detect(CAUSABAS, "B342|U07[1-2]") | str_detect(CODCAUSAS2, "B342|U07[1-2]"))
  
```

## Faixas etárias

```{r}
sim_covid19 <- sim_covid19 %>% 
  mutate(age_group = case_when(
            str_detect(IDADE, "^[0-1]") ~ "Neonatal precoce", # 00-06 days
            str_detect(IDADE, "^20[0-6]") ~ "Neonatal precoce", # 00-06 days
            str_detect(IDADE, "^20[7-9]") ~ "Neonatal tardia", # 07-27 days 
            str_detect(IDADE, "^21[0-9]") ~ "Neonatal tardia", # 07-27 days
            str_detect(IDADE, "^22[0-7]") ~ "Neonatal tardia", # 07-27 days
            str_detect(IDADE, "^22[8-9]") ~ "Neonatal tardia a pré-escolar", # 28-364 days
            str_detect(IDADE, "^3") ~ "Neonatal tardia a pré-escolar", # 28-364 days
            str_detect(IDADE, "^400") ~ "Neonatal tardia a pré-escolar", # 28-364 days
            str_detect(IDADE, "^40[1-4]") ~ "1 a 4 anos", # 01-4 years
            str_detect(IDADE, "^40[5-9]") ~ "5 a 14 anos", # 05-14 years
            str_detect(IDADE, "^41[0-4]") ~ "5 a 14 anos", # 05-14 years
            str_detect(IDADE, "^41[5-9]") ~ "15 a 24 anos", # 15-24 years
            str_detect(IDADE, "^42[0-4]") ~ "15 a 24 anos", # 15-24 years
            str_detect(IDADE, "^42[4-9]") ~ "25 a 34 anos", # 25-34 years
            str_detect(IDADE, "^43[0-4]") ~ "25 a 34 anos", # 25-34 years
            str_detect(IDADE, "^43[5-9]") ~ "35 a 44 anos", # 35-44 years
            str_detect(IDADE, "^44[0-4]") ~ "35 a 44 anos", # 35-44 years
            str_detect(IDADE, "^44[5-9]") ~ "45 a 54 anos", # 45-54 years
            str_detect(IDADE, "^45[0-4]") ~ "45 a 54 anos", # 45-54 years
            str_detect(IDADE, "^45[5-9]") ~ "55 a 64 anos", # 55-64 years
            str_detect(IDADE, "^46[0-4]") ~ "55 a 64 anos", # 55-64 years
            str_detect(IDADE, "^46[5-9]") ~ "65 a 74 anos", # 65-74 years
            str_detect(IDADE, "^47[0-4]") ~ "65 a 74 anos", # 65-74 years
            str_detect(IDADE, "^47[5-9]") ~ "75 a 84 anos", # 75-84 years
            str_detect(IDADE, "^48[0-4]") ~ "75 a 84 anos", # 75-84 years
            TRUE ~ "85 anos ou mais")) %>%
  mutate(age_group = factor(x = age_group, levels = c(
    "Neonatal precoce",
    "Neonatal tardia",
    "Neonatal tardia a pré-escolar",
    "1 a 4 anos",
    "5 a 14 anos",
    "15 a 24 anos",
    "25 a 34 anos",
    "35 a 44 anos",
    "45 a 54 anos",
    "55 a 64 anos",
    "65 a 74 anos",
    "75 a 84 anos",
    "85 anos ou mais"
  )))
```

## Escolaridade

```{r}
sim_covid19 <- sim_covid19 %>% 
  mutate(
    ESC = as.character(levels(ESC))[ESC],
    escolaridade = case_when(
      ESC == 1 ~ "Nenhuma",
      ESC == 2 ~ "1 a 3 anos",
      ESC == 3 ~ "4 a 7 anos",
      ESC == 4 ~ "8 a 11 anos",
      ESC == 5 ~ "12 anos ou mais",
      ESC == 8 ~ "9 a 11 anos",
      ESC == 9 ~ NA_character_
    ),
    escolaridade = factor(x = escolaridade, levels = c(
      "Nenhuma",
      "1 a 3 anos",
      "4 a 7 anos",
      "8 a 11 anos",
      "9 a 11 anos",
      "12 anos ou mais"
    ))
  )
```

## Raça/cor

```{r}
sim_covid19 <- sim_covid19 %>% 
  mutate(
    ESC = as.character(levels(RACACOR))[RACACOR],
    racacor = case_when(
      RACACOR == 1 ~ "Branca",
      RACACOR == 2 ~ "Preta",
      RACACOR == 3 ~ "Amarela",
      RACACOR == 4 ~ "Parda",
      RACACOR == 5 ~ "Indígena",
      RACACOR == 9 ~ "Ignorado"
    ),
    racacor = factor(x = racacor, levels = c(
      "Branca",
      "Preta",
      "Amarela",
      "Parda",
      "Indígena",
      "Ignorado"
    ))
  )
```

## Sexo

```{r}
sim_covid19 <- sim_covid19 %>% 
  mutate(
    SEXO = as.character(levels(SEXO))[SEXO],
    sexo = case_when(
      SEXO == 1 ~ "Masculino",
      SEXO == 2 ~ "Feminino",
      SEXO == 9 ~ "Ignorado"
    ),
    sexo = factor(x = sexo, levels = c(
      "Masculino",
      "Feminino",
      "Ignorado"
    ))
  )
```

## Ocupação

```{r}
sim_covid19 <- sim_covid19 %>% 
  mutate(
    OCUP = as.character(levels(OCUP))[OCUP],
    ocup1 = case_when(
      substr(OCUP, 0, 1) == "0" ~ "Membros das forças armadas, bombeiros e militares",
      substr(OCUP, 0, 1) == "1" ~ "Membros superiores do poder público, dirigentes de organizações de interesse público e de empresas, gerentes",
      substr(OCUP, 0, 1) == "2" ~ "Profissionais das ciências e das artes",
      substr(OCUP, 0, 1) == "3" ~ "Técnicos de nível médio",
      substr(OCUP, 0, 1) == "4" ~ "Trabalhadores de serviços administrativos",
      substr(OCUP, 0, 1) == "5" ~ "Trabalhadores dos serviços, vendedores do comércio em lojas e mercados",
      substr(OCUP, 0, 1) == "6" ~ "Trabalhadores agropecuários, florestais e da pesca",
      substr(OCUP, 0, 1) == "7" ~ "Trabalhadores da produção de bens e serviços industriais",
      substr(OCUP, 0, 1) == "8" ~ "Trabalhadores da produção de bens e serviços industriais",
      substr(OCUP, 0, 1) == "9" ~ "Trabalhadores em serviços de reparação e manutenção"
    ),
    ocup2 = case_when(
      substr(OCUP, 0, 2) == "01" ~ "Membro das forças armadas",
      substr(OCUP, 0, 2) == "02" ~ "Policiais militares",
      substr(OCUP, 0, 2) == "03" ~ "Bombeiros militares",
      substr(OCUP, 0, 2) == "11" ~ "Membros superiores e dirigentes do poder público",
      substr(OCUP, 0, 2) == "12" ~ "Dirigentes de empresas e organizações (exceto de interesse público)",
      substr(OCUP, 0, 2) == "13" ~ "Diretores e gerentes em empresas de serviços de saúde, da educação, ou de serviços culturais, sociais ou pessoais",
      substr(OCUP, 0, 2) == "14" ~ "Gerentes",
      substr(OCUP, 0, 2) == "20" ~ "Pesquisadores e profissionais policientíficos",
      substr(OCUP, 0, 2) == "21" ~ "Profissionais das ciências exatas, físicas e da engenharia",
      substr(OCUP, 0, 2) == "22" ~ "Profissionais das ciências biológicas, da saúde e afins",
      substr(OCUP, 0, 2) == "23" ~ "Profissionais do ensino",
      substr(OCUP, 0, 2) == "24" ~ "Profissionais das ciências jurídicas",
      substr(OCUP, 0, 2) == "25" ~ "Profissionais das ciências humanas",
      substr(OCUP, 0, 2) == "26" ~ "Comunicadores, artistas e religiosos",
      substr(OCUP, 0, 2) == "27" ~ "Profissionais em gastronomia",
      substr(OCUP, 0, 2) == "30" ~ "Técnicos polivalentes",
      substr(OCUP, 0, 2) == "31" ~ "Técnicos de nível médio das ciências físicas, químicas, engenharias e afins",
      substr(OCUP, 0, 2) == "32" ~ "Técnicos de nível médio das ciências biológicas, bioquímicas, da saúde e afins",
      substr(OCUP, 0, 2) == "33" ~ "Professores leigos e de ensino médio",
      substr(OCUP, 0, 2) == "34" ~ "Técnicos de nível médio em serviços de transporte",
      substr(OCUP, 0, 2) == "35" ~ "Técnicos de nível médio nas ciências administrativas",
      substr(OCUP, 0, 2) == "37" ~ "Técnicos de nível médio dos serviços culturais, das comunicações e dos desportos",
      substr(OCUP, 0, 2) == "39" ~ "Outros técnicos de nível médio",
      substr(OCUP, 0, 2) == "41" ~ "Escriturários",
      substr(OCUP, 0, 2) == "42" ~ "Trabalhadores de atendimento ao público",
      substr(OCUP, 0, 2) == "51" ~ "Trabalhadores dos serviços",
      substr(OCUP, 0, 2) == "52" ~ "Vendedores e prestadores de serviços do comércio",
      substr(OCUP, 0, 2) == "61" ~ "Produtores na exploração agropecuária",
      substr(OCUP, 0, 2) == "62" ~ "Trabalhadores na exploração agropecuária",
      substr(OCUP, 0, 2) == "63" ~ "Pescadores e extrativistas florestais",
      substr(OCUP, 0, 2) == "64" ~ "Trabalhadores da mecanização agropecuária e florestal",
      substr(OCUP, 0, 2) == "71" ~ "Trabalhadores da indústria extrativista e da construção civil",
      substr(OCUP, 0, 2) == "72" ~ "Trabalhadores da transformação de metais e de compósitos",
      substr(OCUP, 0, 2) == "73" ~ "Trabalhadores da fabricação e instalação eletroeletrônica",
      substr(OCUP, 0, 2) == "74" ~ "Montadores de aparelhos e instrumentos de precisão e musicais",
      substr(OCUP, 0, 2) == "75" ~ "Joalheiros, vidreiros, ceramistas e afins",
      substr(OCUP, 0, 2) == "76" ~ "Trabalhadores nas indústrias têxtil, do curtimento, do vestuário e das artes gráficas",
      substr(OCUP, 0, 2) == "77" ~ "Trabalhadores das indústrias de madeira e imobiliário",
      substr(OCUP, 0, 2) == "78" ~ "Trabalhadores de funções transversais",
      substr(OCUP, 0, 2) == "79" ~ "Trabalhadores do artesanato",
      substr(OCUP, 0, 2) == "81" ~ "Trabalhadores em indústrias de processos contínuos e outras indústrias",
      substr(OCUP, 0, 2) == "82" ~ "Trabalhadores de instalações siderúrgicas e de materiais de construção",
      substr(OCUP, 0, 2) == "83" ~ "Trabalhadores de instalações e máquinas de fabricação de celulose e papel",
      substr(OCUP, 0, 2) == "84" ~ "Trabalhadores da fabricação de alimentos, bebidas e fumo",
      substr(OCUP, 0, 2) == "86" ~ "Operadores de produção, captação, tratamento e distribuição (energia, água e utilidades)",
      substr(OCUP, 0, 2) == "87" ~ "Operadores de outras instalações industriais",
      substr(OCUP, 0, 2) == "91" ~ "Trabalhadores em serviços de reparação e manutenção",
      substr(OCUP, 0, 2) == "95" ~ "Polimantenedores",
      substr(OCUP, 0, 2) == "99" ~ "Outros trabalhadores da conservação, manutenção e reparação",
      substr(OCUP, 0, 2) == "03" ~ "Bombeiros militares"
    ),
    ocup1 = factor(x = ocup1),
    ocup2 = factor(x = ocup2)
  )
```

## Tratamento geral de campos

```{r}
sim_covid19 <- sim_covid19 %>% 
  mutate(
    DTOBITO = as.Date(x = DTOBITO, format = "%d%m%Y"),
    ano_obito = year(DTOBITO)
  )
```

## Salva arquivo

```{r}
write_rds(x = sim_covid19, file = "../../data/sim_covid19.rds")
```

## Informações da sessão

```{r}
sessionInfo()
```
